### ISSUE TITLE
QUESTION: Support for common actions/feeds/triggers/packages?

### ISSUE THREAD

**Issue by allen-servedio** [serverless/serverless-openwhisk#100]
We will have multiple teams that will want to deploy pipelines of actions/feeds/triggers/packages through which there will be common actions/feeds/triggers/packages that the different teams want to use. Our concerns with deploying and managing such an environment is:

1. Preventing one team from modifying/removing a common component. I guess this boils down to some type of component ownership where what can be done to them can be restricted.

2. Automate the deployment of what is needed in a predictable way. Meaning, if common components are in separate repositories, deploying whatever happens to be in the master branch when moving code between different environments (dev, qa, prod) does not work. It has to be predictable what is being deployed.

3. Last, we are interested in a way for a team to see what the common components are and what their components are (as we are assuming 100's - 1000's of components across all teams combined).

In the wskdeploy spec (https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/specification/openwhisk_v0.9.1.pdf) there is support for what they call dependencies (see around line 521). This feature allows you to add dependencies on other repositories and versions within them. You can then deploy these components to your environment and configure them as needed. I am also hearing suggestions that each team get their own organization (per team) and spaces (for dev, qa, and prod) to segment the components and specify authorization.

Are there any suggested ways to use serverless to accomplish something similar?

**Comment by jthomas** [comment]
These are good questions about managing a larger serverless project but I think the answers fall outside the domain of the framework. Here's my thoughts on the issues raised...

1. If you want to prevent users from accidentally removing services, you will have to investigate the security model provided by OpenWhisk around users, workspaces and packages. I would imagine having namespaces for dev, test & prod. Only certain developers would have access to those workspaces. Deployments for prod and test would only be available through a CI/CD system. You would use the framework to deploy the services through the CI, rather than the dev doing this manually.

2. This would be managed outside of the framework? The CI/CD system would deploy repos based on versions available on release tags. The decision to either have a "mono-repo" or separate repos would be a design choice. The framework doesn't manage this.

3. If you are using common components between teams, they would be exposed as public packages to all teams but only managed by the team developing them? Developers would not need to deploy those services for each application. Apps could then use those services without having to deploy them.

The Serverless Framework does have a huge range of options for importing configuration from other files (https://serverless.com/framework/docs/providers/aws/guide/variables/) but does not support having sub-projects.

If you find any issues supporting your deployment setup with the framework, we can look to make changes to support these. Any changes will be dependent on support within the broader framework.

**Comment by allen-servedio** [comment]
Okay, that pretty much confirms what I am hearing then... To recap:

1. I am also hearing that if we want to isolate who can change something, we basically need to deploy the components into an org and space assigned to the team + environment. And then, as you say, lock down who can deploy where through normal access mechanisms. There is nothing in OpenWhisk that assigns security at the component level.

2. Understood. The serverless framework will not try to go after support for dependencies like the wskdeploy tool is trying to do. It will be configuration and code outside of the framework to setup and manage these dependencies.

3. For this last one, it is a bit more nuanced than what I explained (sorry about that). A simple example could be that we want to expose a package of actions that know how to talk to a database. The users of that would then bind to that package and set their database credentials on it (and then use the bound package to access their database). Or they might want to hook into a generally available trigger (like is done in whisk core with Cloudant). Doing this falls afoul of the points above in that I don't have a way to deploy these components in a "public space" that I can then reference and bind to configure without also installing the components in my org and space. If there was a way to do something similar to the whisk.system package and make them available in different groups and then bind to them, I think that might work... But I don't see a way to do this. So, my plan is to have them install the common components they need into their own org and space and configure them as required.

I am going to close this as you pretty much confirmed my understanding of what is in scope for the serverless framework and what is not. I wanted to confirm what I thought before assuming that was the way to do things. Thanks for your quick input!
