### ISSUE TITLE
Failed to deploy API Gateway route. The requested resource does not exist.

### ISSUE THREAD

**Issue by darko-stoilevski** [serverless/serverless-openwhisk#108]
Hi, 
First of all thank you for the integration plugin, I really appreciate it.

I was testing it out with a local installation of OpenWhisk on an OpenShift cluster (and on a Minishift locally as well) and I get the same error when trying to create an action with an http route.

>   Serverless Error ---------------------------------------
> 
>   Failed to deploy API Gateway route (helloworld) due to error: POST https://openwhisk-faas.127.0.0.1.nip.io/api/v1/web/whisk.system/apimgmt/createApi.http?responsetype=json Returned HTTP 404 (Not Found) --> "The requested resource does not exist."
> 

I'm using the latest versions of all tools:

whisk CLI version       2018-03-28T20:40:42.225+0000
serverless@1.26.1
serverless-openwhisk@0.12.0

I confirm that when using the wsk cli I can specify --web=true and get a url for invocation.

Am I missing something in the configuration on serverless plugin side?

**Comment by jthomas** [comment]
Hello @darko-stoilevski, sorry to hear you've encountered a bug! 

Can you post your `serverless.yml` in here?

Can you also test that you can use the `wsk api create ...` command from the command-line? Web actions are distinct from the API Gateway service and I wonder if the API Gateway service is configured differently on openshift. 

It would also help me if you could run the `deploy` command again with the following env parameter and paste the ouput here.

```
$ DEBUG=needle serverless deploy
```

If this next advice makes sense to you, please follow otherwise ignore! I also could use the logs from the API Gateway container. If you minikube ssh and look for the container using the openwhisk/apigateway image. Use docker logs to retrieve these logs. It should be like this example.

```
==> /var/log/api-gateway/access.log <==
LOGS
==> /var/log/api-gateway/management.log <==
LOGS
==> /var/log/api-gateway/access.log <==
LOGS
```

Finally, do you have simple instructions you followed to set up minishift that I can replicate your setup for testing?

**Comment by dario-rodriguez** [comment]
It seems that you dont have installed the openwhisk packages. Check the packages with:
`wsk package -i list /whisk.system`

The output should be something like:
```
packages
/whisk.system/watson-translator                                        shared
/whisk.system/samples                                                  shared
/whisk.system/github                                                   shared
/whisk.system/watson-speechToText                                      shared
/whisk.system/utils                                                    shared
/whisk.system/slack                                                    shared
/whisk.system/watson-textToSpeech                                      shared
/whisk.system/websocket                                                shared
/whisk.system/weather                                                  shared
/whisk.system/combinators                                              shared
```

**Comment by jthomas** [comment]
As this issue hasn't been updated in a while, I'm going to close it unless you have more details?

**Comment by jthomas** [comment]
I'm closing this as an older issue with no action required at this point.
