### ISSUE TITLE
Can I setup IBM Cloud Object Storage in my serverless.yml

### ISSUE THREAD

**Issue by chearmstrong** [serverless/serverless-openwhisk#124]
Hi.

I have a project that I need to deploy to IBM Cloud Functions (OpenWhisk) - is it possible to setup IBM Cloud Object Storage (IBM's version of S3) in my `serverless.yml` file, like I would do if I was deploying to AWS?

Thanks in advance.

**Comment by jthomas** [comment]
Hello @chearmstrong, thanks for asking about this.

**short answer:** this isn't possible (at the moment). workarounds are available (see below).

**here's the long answer...**

The Serverless Framework uses Cloud Formation to deploy resources listed in the YAML file to AWS. [Cloud Formation](https://aws.amazon.com/cloudformation/) can define Lambda functions but also other AWS resources like S3. The OpenWhisk provider plugin for The Serverless Framework uses the [OpenWhisk platform APIs](https://github.com/apache/incubator-openwhisk/blob/master/docs/rest_api.md) to create serverless resources, rather than an IBM Cloud specific service. IBM Cloud does not have a direct equivalent to AWS Cloud Formation. This means the OpenWhisk plugin can only define OpenWhisk-related resources.

If you need to set up other IBM Cloud services, like Cloud Object Storage, this will have to happen outside the framework. Service credentials created externally can be imported and stored as default parameters on actions.

_I wrote a blog post about manually doing this recently:_ [http://jamesthom.as/blog/2018/06/05/binding-iam-services-to-ibm-cloud-functions/](http://jamesthom.as/blog/2018/06/05/binding-iam-services-to-ibm-cloud-functions/)

### provsioning services

IBM Cloud services can either be provisioned through the [web console](https://console.bluemix.net/catalog/), using the [CLI](https://console.bluemix.net/docs/cli/index.html) or using an "infrastructure-as-code" tool. IBM Cloud has chosen terraform as the official "infrastructure as code" solution for IBM Cloud and [provides an external plugin](https://github.com/IBM-Cloud/terraform-provider-ibm).

- Use one of these options to provision the service and then create service credentails for that instance.

### binding credentials to actions in `serverless.yml`

Service credentials are normally stored as [default parameters](https://github.com/apache/incubator-openwhisk/blob/master/docs/parameters.md#setting-default-parameters-on-an-action) on actions. Default parameters [can be defined](https://github.com/serverless/serverless-openwhisk#runtime-configuration-properties) in the `serverless.yml`. Rather than keeping raw credentials values in the YAML file (and having to check them into source repositories), I would keep the variables in a local file and reference those values using the [framework's variables feature](https://serverless.com/framework/docs/providers/openwhisk/guide/variables#reference-variables-in-other-files). These values will be automatically pulled in at deployment time but don't need to be checked into the code repository. 

_See an example of this approach [here](https://github.com/ibmets/smsbot/blob/master/serverless.yml)._

### improving the developer experience

I know this is a pain for developers and want to provide a better "developer experience" for this common issue.

I've [got an issue open](https://github.com/serverless/serverless-openwhisk/issues/122) to make it easier to bind service credentials to actions. This will automate the process of binding credentials to actions with needing you to manually create a temporary local file. It should be included in the next release, which will be available in a week or two.

**Comment by chearmstrong** [comment]
Thanks for great response - I'll check out those examples you mentioned.

**Comment by jthomas** [comment]
@chearmstrong I've now added the ability to bind to existing services more easily:
https://github.com/serverless/serverless-openwhisk#binding-services-ibm-cloud-functions

Will be available in the next release.

**Comment by chearmstrong** [comment]
@jthomas Awesome - thanks for the update! 👍
