### ISSUE TITLE
serverless-webpack issues when using a sequence

### ISSUE THREAD

**Issue by michaelwclark** [serverless/serverless-openwhisk#125]
When using serverless-webpack and serverless-openwhisk there is a compatibility issue as the serverless getFunction and getHandlerFile do not do any sort of filtering on sequences. This causes serverless-webpack to attempt to validate against a function that does not truly need to be webpacked. I posted the full details of this issue [here](https://github.com/serverless-heaven/serverless-webpack/issues/410) first and was instructed this should be handled on the serverless-openwhisk end of things. 

Is there a known workaround for this? Plans for one? Something that I will need to write up myself? Thanks in advance!

**Comment by jthomas** [comment]
Hello Michael, thanks for opening this issue. 

OpenWhisk does introduce functions without handlers, which are valid in OpenWhisk but not something the external plugin supports.

I'm not familiar with webpack (so forgive any mistakes) but reading the repo, I have a few ideas... 

- It looks like you are using [auto-entry resolution](https://github.com/serverless-heaven/serverless-webpack#automatic-entry-resolution) from the ticket. Is it possible to manually define the entry points and remove the sequence? 

It this doesn't work, the best solution would be to enhance the webpack plugin to ignore functions without handlers, rather than dying. Changing how sequences are defined in the OpenWhisk plugin would be a huge amount of work and doesn't make sense IMO.

If you want to pull me into a discussion with the other plugin provider, let me know. 

Sorry I don't have a quick solution!

**Comment by michaelwclark** [comment]
I figured this would end up being a bit of a custom code job. Unfortunatly the auto-entry resolution is only a piece of the puzzle as the serverless-webpack is doing some validations of serverless.yml at instantiation even before getting to auto entries.  

Long term I may dig into the codebase over there and submit a PR or (*cringe*) fork and fix for our use case. 

Other than webpack for building assets and dependancies do you have other recomendations, or do most people just skip that step with serverless?

**Comment by jthomas** [comment]
@michaelwclark Some people have suggested other tools to me before like Rollupjs or Parceljs. This would require a manual setup rather than auto-magic plugins. 

TBH I would deploy your functions unoptimised and then performance test to see if you need the performance improvements and how much it would bring. My feeling is that it'll be minimal tbh.

Going to close this as `wontfix` because this is an important issue, I don't see a fix in this module at the moment. Will re-open if something changes. Thanks for looking into this!
