### ISSUE TITLE
__ow_path is blank in API created with response type http

### ISSUE THREAD

**Issue by PallaviPatil2** [serverless/serverless-openwhisk#136]
We have created 2 APIs in same base path as shown below.
1.  ibmcloud fn api create /v1/abc/ka /assets/upload/{aaid}/name/{name} get 'serverless-files/presign' --response-type http

2.  ibmcloud fn api create /v1/abc/ka /metadata post 'ams-cloudant/validate_seq' --response-type http

For the 1st API with presign I am able to read __ow_path and its returning /v1/abc/ka/assets/upload/1234/name/test.pdf .
The same code I am using in 2nd API, but ow_path is blank..it should return /v1/abc/ka/metadata right?
May I know why ow_path is blank in 2nd case.

**Comment by jthomas** [comment]
Did you use the serverless framework openwhisk plugin to create these APIs? From the description above, it looks like you are using the CLI. Support for OpenWhisk related issues, rather than the serverless framework plugin, needs to use one of the support channels for that project...
- [Stack Overflow](https://stackoverflow.com/questions/tagged/ibm-cloud-functions)
- [Slack](http://openwhisk.incubator.apache.org/slack.html)
- [IBM Cloud Support](https://www.ibm.com/cloud/support/support)

**Comment by csantanapr** [comment]
@PallaviPatil2 
This should be fixed now, also fixed if you IBM Cloud Functions.
https://github.com/apache/incubator-openwhisk/issues/4055
Just update your apis with `wsk api create` or `ibmcloud fn api create`
