### ISSUE TITLE
Add Swift plugin for automatic compilation

### ISSUE THREAD

**Issue by jthomas** [serverless/serverless-openwhisk#49]
Swift execution can be speed up by compiling and deploying the binary, rather than the source files.

Using Docker to run the container locally, users can build the executable for the correct runtime. This approach is detailed here:
https://github.com/openwhisk/openwhisk/blob/master/docs/actions.md#packaging-an-action-as-a-swift-executable

As this relies on Docker and external images, having this as the main compilation step for Swift files is not realistic. However, it would be possible to write a new serverless fw plugin that hooked into the build step and performed this automatically.

**Comment by akrabat** [comment]
A plugin makes sense. It's certainly a requirement for using Swift in OpenWhisk as it cuts the cold-start time by a couple of seconds.

https://github.com/SwiftOnTheServer/flashcards/blob/master/api/compile.sh is how I currently do it. 

Additional thoughts:

1. The file containing the function must be called `main.swift` in the Docker container as otherwise the compiler won't build it. See [lines 18-21](https://github.com/SwiftOnTheServer/flashcards/blob/677f3e09514faf08c1b0f34efee430c051eefef8/api/compile.sh#L18-L21)
2. if a `Package.swift` exists, then the action uses Swift's Package Manager for dependencies and it would be lovely is that was also supported. See [lines 28-32](https://github.com/SwiftOnTheServer/flashcards/blob/677f3e09514faf08c1b0f34efee430c051eefef8/api/compile.sh#L28-L32)

**Comment by jthomas** [comment]
This feature can be achieved with the new [OpenWhisk Swift package](https://github.com/jthomas/OpenWhiskAction), Docker and NPM scripts. I've created an example using this approach here:
https://github.com/serverless/examples/tree/master/openwhisk-swift-precompiled-binaries

The `npm run-script compile` will running the following command.
```
docker run --rm -it -v $(pwd):/swift-package openwhisk/swift3action bash -e -c 'cd /swift-package && swift build -v -c release'
```

Using the `serverless-plugin-scripts` plugin, we can execute this command each time the package event is emitted. 

```yml
custom:
  scripts:
    hooks:
      'package:initialize': npm run-script compile

plugins:
  - serverless-openwhisk
  - serverless-plugin-scripts
```
