### ISSUE TITLE
On Ubuntu, "npm install -g serverless serverless-openwhisk" fails during postinstall 

### ISSUE THREAD

**Issue by l2fprod** [serverless/serverless-openwhisk#78]
My setup involves running Ubuntu 16.04 as a Docker container on macOS

`npm install --global serverless serverless-openwhisk` leads to:
```
> spawn-sync@1.0.15 postinstall /root/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/spawn-sync
> node postinstall

sh: 1: node: Permission denied
```

Installing with `npm install --global serverless serverless-openwhisk --unsafe-perm spawn-sync` solves the issue.

Similar problem when running `npm install` in the project to link the serverless module.

```
~/mnt/home/tmp/hello-serverless-fw> npm install
npm WARN lifecycle openwhisk-nodejs@1.0.0~postinstall: cannot run in wd %s %s (wd=%s) openwhisk-nodejs@1.0.0 npm link serverless-openwhisk /root/mnt/home/tmp/hello-serverless-fw
npm WARN openwhisk-nodejs@1.0.0 No repository field.
npm WARN openwhisk-nodejs@1.0.0 No license field.
```

Running `npm install --unsafe-perm` solves this one too.

**Comment by jthomas** [comment]
Thanks for raising this and providing the context. This is an [known issue with NPM and Docker](https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd), rather than this library. I'll closing this ticket as it's not something we can fix. 

Hopefully if other people come across this your explanation and solution will be perfect.
