### ISSUE TITLE
Add Support For Java Runtimes

### ISSUE THREAD

**Issue by allen-servedio** [serverless/serverless-openwhisk#93]
Per what I see in https://github.com/serverless/serverless-openwhisk/blob/master/compile/functions/runtimes/index.js it does not appear that this plugin support Java runtimes. 

OpenWhisk does support this runtime: https://github.com/apache/incubator-openwhisk-runtime-java

**Comment by jthomas** [comment]
@allen-servedio you're the first person to ask for this :) 

Is this something you need or just wondering why it isn't implemented? Java is much less popular on serverless platforms due to the startup latency.

It shouldn't be a huge fix to add this. I haven't used the Java runtime so I need to check out how it works.

**Comment by allen-servedio** [comment]
We are in the process of looking to move an existing code base into IBM Cloud Functions... A large portion of this code base is in Java and so we are interested in using the Java runtime for that. Definitely willing to work with you and help out to get this done.
